import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { useTranslation } from "@/i18n/useTranslation";
import { MultiplayerPanel } from "@/multiplayer/MultiplayerPanel";
import { useMultiplayerLobby } from "@/multiplayer/useMultiplayerLobby";
import type { BaseMultiplayerMessage } from "@/multiplayer/messages";
import "./generally.css";
import { DEFAULT_TRACK, DEFAULT_VEHICLE, SURFACES, applyRemoteSnapshot, createInitialCar, createInitialRace, createSnapshot, sampleHeight, sampleSurface, stepCar, type CarState, type GenerallyNetworkSnapshot, type RaceInput, type RaceMode, type RaceState, type SurfaceId, type TrackDecoration } from "./generally.logic";

type GenerallySnapshotMessage = BaseMultiplayerMessage<"generally:snapshot"> & { snapshot: GenerallyNetworkSnapshot };
type GenerallyStartMessage = BaseMultiplayerMessage<"generally:start"> & { mode: RaceMode };
type GenerallyMessage = GenerallySnapshotMessage | GenerallyStartMessage;
type MeshMap = Record<string, THREE.Group>;
const FRAME_DT_LIMIT = 1 / 20;
const SNAPSHOT_INTERVAL_MS = 90;
const MODE_LABELS: Record<RaceMode, string> = { singleplayer: "Singleplayer", timeTrial: "Time Trial", hotSeat: "Hot Seat", online: "Online" };
const SURFACE_COLORS: Record<SurfaceId, number> = { asphalt: 0x4d555d, grass: 0x6dbb4d, sand: 0xd8bf79, gravel: 0x9b9285, mud: 0x76513b, ice: 0xb4e7ff };
const keysToInput = (keys: ReadonlySet<string>, secondPlayer = false): RaceInput => ({ throttle: keys.has(secondPlayer ? "i" : "arrowup") || (!secondPlayer && keys.has("w")) ? 1 : 0, brake: keys.has(secondPlayer ? "k" : "arrowdown") || (!secondPlayer && keys.has("s")) ? 1 : 0, steer: (keys.has(secondPlayer ? "j" : "arrowleft") || (!secondPlayer && keys.has("a")) ? 1 : 0) - (keys.has(secondPlayer ? "l" : "arrowright") || (!secondPlayer && keys.has("d")) ? 1 : 0) });
const formatTime = (seconds: number | null): string => { if (seconds === null) return "--:--"; const minutes = Math.floor(seconds / 60); return `${minutes}:${(seconds - minutes * 60).toFixed(2).padStart(5, "0")}`; };
function makeCarMesh(color: string): THREE.Group { const group = new THREE.Group(); const body = new THREE.Mesh(new THREE.BoxGeometry(2.2, 0.55, 3.4), new THREE.MeshStandardMaterial({ color })); body.position.y = 0.5; const cockpit = new THREE.Mesh(new THREE.BoxGeometry(1.2, 0.45, 1.35), new THREE.MeshStandardMaterial({ color: 0xf6f7ff })); cockpit.position.set(0, 0.95, -0.25); const nose = new THREE.Mesh(new THREE.BoxGeometry(1.35, 0.25, 0.7), new THREE.MeshStandardMaterial({ color: 0x111827 })); nose.position.set(0, 0.8, 1.45); group.add(body, cockpit, nose); return group; }
function createTerrainMesh(): THREE.Mesh { const rows = DEFAULT_TRACK.heightMap.length, cols = DEFAULT_TRACK.heightMap[0].length; const geometry = new THREE.PlaneGeometry(DEFAULT_TRACK.width, DEFAULT_TRACK.depth, cols - 1, rows - 1); geometry.rotateX(-Math.PI / 2); const colors: number[] = []; const color = new THREE.Color(); const position = geometry.getAttribute("position"); for (let i = 0; i < position.count; i += 1) { const x = position.getX(i), z = position.getZ(i); position.setY(i, sampleHeight(DEFAULT_TRACK, x, z)); color.setHex(SURFACE_COLORS[sampleSurface(DEFAULT_TRACK, x, z).id]); colors.push(color.r, color.g, color.b); } geometry.setAttribute("color", new THREE.Float32BufferAttribute(colors, 3)); geometry.computeVertexNormals(); return new THREE.Mesh(geometry, new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.95 })); }
function createDecorationMesh(decoration: TrackDecoration): THREE.Object3D { const y = sampleHeight(DEFAULT_TRACK, decoration.position.x, decoration.position.z); if (decoration.kind === "tree") { const group = new THREE.Group(); const trunk = new THREE.Mesh(new THREE.CylinderGeometry(0.35, 0.45, 2.2, 8), new THREE.MeshStandardMaterial({ color: 0x6b4423 })); trunk.position.y = 1.1; const crown = new THREE.Mesh(new THREE.ConeGeometry(1.65, 3.2, 10), new THREE.MeshStandardMaterial({ color: 0x285f32 })); crown.position.y = 3.15; group.add(trunk, crown); group.position.set(decoration.position.x, y, decoration.position.z); return group; } if (decoration.kind === "building") { const mesh = new THREE.Mesh(new THREE.BoxGeometry(6, 4, 5), new THREE.MeshStandardMaterial({ color: 0xd6d0c6 })); mesh.position.set(decoration.position.x, y + 2, decoration.position.z); return mesh; } const radius = decoration.kind === "tyres" ? 1.1 : 0.45, height = decoration.kind === "tyres" ? 0.65 : 2.4, mesh = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, height, 16), new THREE.MeshStandardMaterial({ color: decoration.kind === "tyres" ? 0x20242a : 0xf2f2f2 })); mesh.position.set(decoration.position.x, y + height / 2, decoration.position.z); return mesh; }
function createScene(canvas: HTMLCanvasElement) { const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); const scene = new THREE.Scene(); scene.background = new THREE.Color(0xdcefff); const camera = new THREE.OrthographicCamera(-52, 52, 38, -38, 1, 240); camera.position.set(0, 82, 68); camera.lookAt(0, 0, 0); scene.add(new THREE.HemisphereLight(0xffffff, 0x8cad7b, 2.1)); const sun = new THREE.DirectionalLight(0xffffff, 2.4); sun.position.set(-35, 70, 25); scene.add(sun); scene.add(createTerrainMesh()); for (const decoration of DEFAULT_TRACK.decorations) scene.add(createDecorationMesh(decoration)); const finish = new THREE.Mesh(new THREE.BoxGeometry(18, 0.08, 0.6), new THREE.MeshStandardMaterial({ color: 0xffffff })); finish.position.set(0, sampleHeight(DEFAULT_TRACK, 0, DEFAULT_TRACK.finishLineZ) + 0.08, DEFAULT_TRACK.finishLineZ); scene.add(finish); return { renderer, scene, camera, carMeshes: {} as MeshMap }; }
function syncCarMeshes(sceneState: ReturnType<typeof createScene>, cars: CarState[]): void { for (const car of cars) { let mesh = sceneState.carMeshes[car.id]; if (!mesh) { mesh = makeCarMesh(car.color); sceneState.carMeshes[car.id] = mesh; sceneState.scene.add(mesh); } mesh.position.set(car.position.x, car.position.y + 0.3, car.position.z); mesh.rotation.set(car.airborne ? -0.08 : 0, car.yaw, 0); } }
export default function GenerallyGame(): React.ReactElement { const { t } = useTranslation(); const canvasRef = useRef<HTMLCanvasElement | null>(null); const sceneRef = useRef<ReturnType<typeof createScene> | null>(null); const keysRef = useRef<Set<string>>(new Set()); const raceRef = useRef<RaceState>(createInitialRace("singleplayer")); const lastSnapshotRef = useRef(0); const [race, setRace] = useState<RaceState>(() => raceRef.current); const [mode, setMode] = useState<RaceMode>("singleplayer"); const [menuOpen, setMenuOpen] = useState(true); const [status, setStatus] = useState(t("generally.status.ready"));
  const startRace = useCallback((nextMode: RaceMode) => { const initial = createInitialRace(nextMode); raceRef.current = initial; setRace(initial); setMode(nextMode); setMenuOpen(false); setStatus(nextMode === "online" ? t("generally.status.online") : t("generally.status.racing")); }, [t]);
  const lobby = useMultiplayerLobby<GenerallyMessage>({ onGameMessage: (message) => { if (message.type === "generally:snapshot") raceRef.current = { ...raceRef.current, cars: mergeRemoteCar(raceRef.current.cars, message.snapshot) }; if (message.type === "generally:start") startRace(message.mode); } });
  const canUseOnline = mode === "online"; const localCar = race.cars[0]; const sortedCars = useMemo(() => [...race.cars].sort((a, b) => b.lap - a.lap || b.checkpoint - a.checkpoint || a.raceTime - b.raceTime), [race.cars]);
  const broadcast = useCallback((message: Omit<GenerallyMessage, "sentAt" | "senderId">): void => { if (canUseOnline) lobby.sendMessage(message); }, [canUseOnline, lobby]);
  function mergeRemoteCar(cars: CarState[], snapshot: GenerallyNetworkSnapshot): CarState[] { if (snapshot.id === "player-1") return cars; const existing = cars.find((car) => car.id === snapshot.id); if (existing) return cars.map((car) => (car.id === snapshot.id ? applyRemoteSnapshot(car, snapshot) : car)); const remote = createInitialCar(snapshot.id, "Gracz online", "#1e88e5", 2.2, "remote"); return [...cars, applyRemoteSnapshot(remote, snapshot, 1)]; }
  function startAndBroadcast(nextMode: RaceMode): void { startRace(nextMode); if (nextMode === "online") broadcast({ type: "generally:start", mode: nextMode }); }
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { const key = event.key.toLowerCase(); keysRef.current.add(key); if (key === "escape") setMenuOpen((open) => !open); if (key === "r") { startRace(mode); if (mode === "online") broadcast({ type: "generally:start", mode }); } }; const onKeyUp = (event: KeyboardEvent) => keysRef.current.delete(event.key.toLowerCase()); window.addEventListener("keydown", onKeyDown); window.addEventListener("keyup", onKeyUp); return () => { window.removeEventListener("keydown", onKeyDown); window.removeEventListener("keyup", onKeyUp); }; }, [mode, broadcast, startRace]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const sceneState = createScene(canvas); sceneRef.current = sceneState; let frame = 0, previous = performance.now(); const resize = () => { const parent = canvas.parentElement, width = parent?.clientWidth ?? 900, height = parent?.clientHeight ?? 640, aspect = width / Math.max(height, 1), viewHeight = 76; sceneState.renderer.setSize(width, height, false); sceneState.camera.left = (-viewHeight * aspect) / 2; sceneState.camera.right = (viewHeight * aspect) / 2; sceneState.camera.top = viewHeight / 2; sceneState.camera.bottom = -viewHeight / 2; sceneState.camera.updateProjectionMatrix(); }; resize(); window.addEventListener("resize", resize); const loop = (now: number) => { const dt = Math.min((now - previous) / 1000, FRAME_DT_LIMIT); previous = now; const current = raceRef.current; const nextCars = current.cars.map((car, index) => car.controller === "remote" ? car : stepCar(car, keysToInput(keysRef.current, index === 1), dt, DEFAULT_TRACK, DEFAULT_VEHICLE, current.totalLaps)); const nextRace = { ...current, cars: nextCars, elapsed: current.elapsed + dt }; raceRef.current = nextRace; syncCarMeshes(sceneState, nextRace.cars); sceneState.renderer.render(sceneState.scene, sceneState.camera); if (now - lastSnapshotRef.current > SNAPSHOT_INTERVAL_MS && mode === "online") { lastSnapshotRef.current = now; broadcast({ type: "generally:snapshot", snapshot: createSnapshot(nextRace.cars[0], Date.now()) }); } setRace(nextRace); frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop); return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); sceneState.renderer.dispose(); }; }, [broadcast, mode]);
  return <div className="generally-shell"><div className="generally-stage"><canvas ref={canvasRef} className="generally-canvas" aria-label={t("generally.canvasLabel")} />{menuOpen ? <div className="generally-menu"><h2>{t("generally.title")}</h2><p>{t("generally.subtitle")}</p><div className="generally-mode-grid">{(["singleplayer", "timeTrial", "hotSeat", "online"] as RaceMode[]).map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{MODE_LABELS[item]}</button>)}</div>{mode === "online" ? <MultiplayerPanel lobby={lobby} minPlayers={2} maxPlayers={4} /> : null}<button className="generally-primary" onClick={() => startAndBroadcast(mode)}>{t("generally.start")}</button></div> : null}</div><aside className="generally-hud"><header><strong>{MODE_LABELS[mode]}</strong><span>{status}</span></header><dl><div><dt>{t("generally.lap")}</dt><dd>{localCar?.lap ?? 1}/{race.totalLaps}</dd></div><div><dt>{t("generally.position")}</dt><dd>{Math.max(1, sortedCars.findIndex((car) => car.id === localCar?.id) + 1)}/{race.cars.length}</dd></div><div><dt>{t("generally.currentLap")}</dt><dd>{formatTime(localCar?.currentLapTime ?? 0)}</dd></div><div><dt>{t("generally.bestLap")}</dt><dd>{formatTime(localCar?.bestLapTime ?? null)}</dd></div><div><dt>{t("generally.surface")}</dt><dd>{localCar ? SURFACES[sampleSurface(DEFAULT_TRACK, localCar.position.x, localCar.position.z).id].name : "--"}</dd></div></dl><div className="generally-controls"><p>{t("generally.controls.main")}</p><p>{t("generally.controls.hotseat")}</p></div>{race.cars.some((car) => car.finished) ? <div className="generally-results"><h3>{t("generally.results")}</h3>{sortedCars.map((car, index) => <div key={car.id}><span>{index + 1}. {car.name}</span><strong>{formatTime(car.raceTime)}</strong></div>)}</div> : null}</aside></div>;
}
